### ISSUE TITLE
2nd Review of AOO41GS3.odt

### ISSUE THREAD

**Issue by DiGro** [apache/openoffice-docs#33]
Pulled the reviewed AOO41GS3 from the repository of FJCC

Changed template to AOOdoc
Reviewed the file (found several instances of Liberation Sans font instead of DejaVu Serif)

Reviewed file is attached to this issue as a ZIP (change extension back to odt to make it work again)

[AOO41GS3_digro_202100328.zip](https://github.com/apache/openoffice-docs/files/6217352/AOO41GS3_digro_202100328.zip)

**Comment by orcmid** [comment]
I still don't understand the comment about needing to use a Zip instead of an odt.  There are numerous .odt files in this repository.  Is the complaint about making an .odt an attachment in an issue or a pull request?

I also notice that there are still no `.gitignore` and `.gitattribute` files in this repository and any of its "branches."

(Aside: I fear you are going to get burned by the use of branches where directories should have been used.  At some point, this is going to be unrecoverable.  The ability to use branches for development of focused/confined changes and then merging into the main has been lost.  Please look at any of the guides about using Git and GitHub to manage projects.)

**Comment by FJCC** [comment]
I applied all of DiGro's  edits.

**Comment by knmc** [comment]
Reviewed and is ready for publication.
