### ISSUE TITLE
Table of Contents for AOO41GS.odt Cannot be used to go directly to a location in the Document

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#91]
When you update the Table of Contents, the links are not clickable and do not jump to the linked location in the document. As my system is having problems, this needs to be checked to see if it is just my system being flackey, or is a problem with AOO version 4.1.13.

**Comment by jeanweber42** [comment]
The settings for the TOC in that file do not include hyperlinks. The problem is not in your system, or in AOO. 

To add the necessary hyperlinks, right-click on the TOC, choose Edit, go to the Entries page, and add a hyperlink at the beginning and end of the Structure line. Click All at the end of that line to apply the changes to all levels of the TOC. Click OK to save the change.

**Comment by knmc** [comment]
Closed TOC is now working.
